---
apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: tls-wildcard
  namespace: formbuilder-services-{{ .Values.environmentName }}
spec:
  secretName: tls-certificate
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: '*.{{ .Values.platformEnvironment }}.form.service.justice.gov.uk'
  acme:
    config:
    - domains:
      - '*.{{ .Values.platformEnvironment }}.form.service.justice.gov.uk'
      dns01:
        provider: route53-cloud-platform
