---
apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: tls-wildcard
  namespace: formbuilder-services-{{ .Values.environmentName }}
spec:
  secretName: tls-certificate
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: '{{ .Values.wildcard_domain }}'
  acme:
    config:
    - domains:
      - '{{ .Values.wildcard_domain }}'
      dns01:
        provider: route53-cloud-platform
