# Bind admin role for namespace to team group
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: formbuilder-publisher-{{ .Values.environmentName }}-admins
  namespace: formbuilder-publisher-{{ .Values.environmentName }}
subjects:
  - kind: Group
    name: "github:form-builder"
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: admin
  apiGroup: rbac.authorization.k8s.io
